name: Pipeline
on:
  workflow_call:
    secrets:
      SECRET_KEY:
        required: true

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Copy repository files
        uses: actions/checkout@v5

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - name: Install Poetry
        run: pipx install poetry

      - name: Install dependences
        run: poetry install

      - name: Run lint
        run: poetry run task lint

  test:
    needs: lint
    runs-on: ubuntu-latest

    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    steps:
      - name: Copy repository files
        uses: actions/checkout@v5

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - name: Install Poetry
        run: pipx install poetry

      - name: Install dependences
        run: poetry install

      - name: Run tests
        run: poetry run task test